apiVersion: v1
kind: Service
metadata:
  name: lanchonete-app-service
  labels:
    app: lanchonete-app
spec:
  selector:
    app: lanchonete-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer
