apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: SecretStore
  target:
    name: mysql-secret
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_ROOT_PASSWORD 
      remoteRef:
        key: MySqlRootPassword 
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: MySqlDatabase
    - secretKey: MYSQL_USER
      remoteRef:
        key: MySqlUser
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: MySqlPassword