apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.service.name }}
  namespace: default
spec:
  refreshInterval: 1h 
  secretStoreRef:
    name: azure-keyvault-store
    kind: SecretStore
  target:
    name: {{ .Values.service.name }}
    creationPolicy: Owner 
  data:
    - secretKey: MERCADOPAGO_CLIENT_ID 
      remoteRef:
        key: MercadoPagoClientId 
    - secretKey: MERCADOPAGO_SECRET_ID
      remoteRef:
        key: MercadoPagoSecretId
    - secretKey: database-user
      remoteRef:
        key: MySqlUser
    - secretKey: database-password
      remoteRef:
        key: MySqlPassword
    - secretKey: database-name
      remoteRef:
        key: MySqlDatabase
    - secretKey: database-host
      remoteRef:
        key: MySqlHost